name: Sync Image to Aliyun

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Aliyun Container Registry
        uses: docker/login-action@v3
        with:
          registry: crpi-5nhti4u3n1folqgv.cn-beijing.personal.cr.aliyuncs.com
          username: ${{ secrets.ALIYUN_USERNAME }}
          password: ${{ secrets.ALIYUN_PASSWORD }}
      
      - name: Pull and push image
        run: |
          docker pull nginx:latest
          docker tag nginx:latest crpi-5nhti4u3n1folqgv.cn-beijing.personal.cr.aliyuncs.com/irober/nginx:latest
          docker push crpi-5nhti4u3n1folqgv.cn-beijing.personal.cr.aliyuncs.com/irober/nginx:latest
