name: Sync Image to Aliyun

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Install skopeo
        run: |
          sudo apt-get update
          sudo apt-get install -y skopeo
      
      - name: Login to Aliyun Container Registry
        run: |
          skopeo login --username ${{ secrets.ALIYUN_USERNAME }} \
            --password ${{ secrets.ALIYUN_PASSWORD }} \
            crpi-5nhti4u3n1folqgv.cn-beijing.personal.cr.aliyuncs.com

      - name: Sync image
        run: |
          skopeo copy docker://docker.io/library/nginx:latest \
            docker://crpi-5nhti4u3n1folqgv.cn-beijing.personal.cr.aliyuncs.com/irober/nginx:latest
